version: '3.1'
services:
  # Postgres
  test-postgres:
    image: postgres:12.7
    container_name: test-postgres
    env_file: ./config/postgres.env
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - local-postgres:/var/lib/postgresql/data
volumes:
  local-postgres: